server:
  port: 9999
spring:
  application:
      name: ReadCsv
  datasource:
    url: jdbc:mysql://8.149.129.178:3306/market
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 111
  jpa:
      show-sql: false
      hibernate:
        ddlAuto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
