server:
  port: 9999
spring:
  application:
      name: ReadCsv
  datasource:
    url: jdbc:mysql://8.149.129.178/market
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 111
